# Generated by Django 2.2.2 on 2019-08-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190819_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='attachment_path',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='课件路径'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.SmallIntegerField(choices=[(0, '付费'), (1, 'VIP专享'), (2, '学位课程'), (4, '免费')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='名称'),
        ),
    ]
